const EXERCICES = [
	{
		abs: [
			{
				group: "abs",
				name: "Скручивания",
				imgSrc: "img/exercices/abs/abs-1.webp",
				instructions: "",
			},
			{
				group: "abs",
				name: "Обратные скручивания",
				imgSrc: "img/exercices/abs/abs-2.webp",
				instructions: "",
			},
			{
				group: "abs",
				name: "Косые скручивания",
				imgSrc: "img/exercices/abs/abs-3.webp",
				instructions: "",
			},
			{
				group: "abs",
				name: "Подъём ног в висе",
				imgSrc: "img/exercices/abs/abs-4.webp",
				instructions: "",
			},
			{
				group: "abs",
				name: "Подъём ног в упоре на локтях",
				imgSrc: "img/exercices/abs/abs-5.webp",
				instructions: "",
			},
		],
		back: [
			{
				group: "back",
				name: "Вертикальная тяга широким хватом",
				imgSrc: "img/exercices/back/back-1.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Вертикальная тяга обратным хватом",
				imgSrc: "img/exercices/back/back-2.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Горизонтальная тяга",
				imgSrc: "img/exercices/back/back-3.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Подтягивания на перекладине",
				imgSrc: "img/exercices/back/back-4.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Гиперэкстензия",
				imgSrc: "img/exercices/back/back-5.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Тяга гантели одной рукой в наклоне",
				imgSrc: "img/exercices/back/back-6.webp",
				instructions: "",
			},
			{
				group: "back",
				name: "Обратные разведения рук",
				imgSrc: "img/exercices/back/back-7.webp",
				instructions: "",
			},
		],
		biceps: [
			{
				group: "biceps",
				name: "Молоток",
				imgSrc: "img/exercices/biceps/biceps-1.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Подъём гантелей в скамье Скотта",
				imgSrc: "img/exercices/biceps/biceps-2.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Подъём гантелей стоя",
				imgSrc: "img/exercices/biceps/biceps-3.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Подъём штанги обратным хватом",
				imgSrc: "img/exercices/biceps/biceps-4.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Подъем штанги стоя",
				imgSrc: "img/exercices/biceps/biceps-5.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Сгибание рук в запястьях",
				imgSrc: "img/exercices/biceps/biceps-6.webp",
				instructions: "",
			},
			{
				group: "biceps",
				name: "Концентрированный подъем на бицепс",
				imgSrc: "img/exercices/biceps/biceps-7.webp",
				instructions: "",
			},
		],
		chest: [
			{
				group: "chest",
				name: "Жим штанги лёжа",
				imgSrc: "img/exercices/chest/chest-1.webp",
				instructions: "",
			},
			{
				group: "chest",
				name: "Жим гантелей лёжа",
				imgSrc: "img/exercices/chest/chest-2.webp",
				instructions: "",
			},
			{
				group: "chest",
				name: "Жим от груди в тренажере лежа",
				imgSrc: "img/exercices/chest/chest-3.webp",
				instructions: "",
			},
			{
				group: "chest",
				name: "Разведения гантелей лежа",
				imgSrc: "img/exercices/chest/chest-4.webp",
				instructions: "",
			},
			{
				group: "chest",
				name: "Сведения рук в тренажере бабочка",
				imgSrc: "img/exercices/chest/chest-5.webp",
				instructions: "",
			},
			{
				group: "chest",
				name: "Отжимания от пола",
				imgSrc: "img/exercices/chest/chest-6.webp",
				instructions: "",
			},
		],
		legs: [
			{
				group: "legs",
				name: "Разгибание ног",
				imgSrc: "img/exercices/legs/legs-1.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Сгибание ног лежа",
				imgSrc: "img/exercices/legs/legs-2.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Сгибание ног сидя",
				imgSrc: "img/exercices/legs/legs-3.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Вышагивания на платформу",
				imgSrc: "img/exercices/legs/legs-4.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Гак-приседания",
				imgSrc: "img/exercices/legs/legs-5.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Жим ногами",
				imgSrc: "img/exercices/legs/legs-6.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Выпады с гантелями",
				imgSrc: "img/exercices/legs/legs-7.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Подъемы на носки стоя",
				imgSrc: "img/exercices/legs/legs-8.webp",
				instructions: "",
			},
			{
				group: "legs",
				name: "Подъемы на носки в тренажере",
				imgSrc: "img/exercices/legs/legs-9.webp",
				instructions: "",
			},
		],
	},
];
